//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T8_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StuID { get; set; }
        public string StuName { get; set; }
        public string StuLoginName { get; set; }
        public string StuLoginPwd { get; set; }
        public bool StuSex { get; set; }
        public string StuPhone { get; set; }
        public string StuEmail { get; set; }
        public string StuGrade { get; set; }
    }
}
