//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherLoginName { get; set; }
        public string TeacherLoginPwd { get; set; }
        public string TeacherPhone { get; set; }
        public string TeacherEmail { get; set; }
    }
}
