//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        public int StuID { get; set; }

        //必填项
        [Required]
        public string Name { get; set; }

        [Required(ErrorMessage = "密码是必填项")]
        [RegularExpression("[a-z0-9A-Z]{6,12}", ErrorMessage = "密码只能数字和字母组成的6-12的字符")]
        public string Password { get; set; }

        public string Sex { get; set; }
        public Nullable<int> Grades { get; set; }


        //[MaxLength(50)]
        [StringLength(50, ErrorMessage = "字符长度在50字之内")]
        public string Intro { get; set; }

        public string Agreest { get; set; }

        [Required]
        [Compare("Password", ErrorMessage = "两次输入密码不一致")]
        public string Password2 { get; set; }
        [Required(ErrorMessage = "年龄为必填项")]
        [Range(typeof(int), "10", "30", ErrorMessage = "年龄在10-30岁之间")]
        public Nullable<int> Age { get; set; }

        public virtual Grades Grades1 { get; set; }
    }
}
